name: a_bientot
description: A smart travel deal planner.
publish_to: 'none' # Remove if publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase (Dart 3 compatible, Web support)
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  cloud_functions: ^4.7.6
  flutter_local_notifications: ^16.0.0
  # UI & state
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  flutter_typeahead: ^5.2.0
  intl: ^0.20.2

  http: ^0.13.5
  shared_preferences: ^2.2.2
  # Search
  algolia: ^1.1.1

  # Optional: keyboard visibility if still needed
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logos/
    - assets/data/airports.json
    - assets/data/airlines.json
